import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  topSceneFade: { position: "absolute", top: 0, left: 0, right: 0, height: 168, zIndex: 11 },
  bottomSceneFade: { position: "absolute", left: 0, right: 0, bottom: 0, height: 220, zIndex: 11 },
  searchCard: {
    position: "absolute",
    left: 16,
    right: 16,
    zIndex: 18,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
    shadowColor: "#0f172a",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  searchLabel: { fontSize: 11, fontWeight: "800", textTransform: "uppercase", letterSpacing: 1.1, marginBottom: 6 },
  searchInputRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  searchInputIconWrap: { width: 34, height: 34, borderRadius: 999, alignItems: "center", justifyContent: "center" },
  searchInput: { flex: 1, fontSize: 16, paddingVertical: 8, fontWeight: "600" },
  searchFeedback: {
    position: "absolute",
    left: 22,
    right: 22,
    zIndex: 18,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  myLocationButton: {
    width: 48,
    height: 48,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0f172a",
    shadowOpacity: 0.14,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
  },
  mapUtilityRow: {
    position: "absolute",
    zIndex: 18,
    right: 18,
    flexDirection: "column",
    gap: 10,
  },
  bottomBar: {
    position: "absolute",
    zIndex: 18,
    borderRadius: 28,
    borderWidth: 1,
    padding: 10,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    shadowColor: "#0f172a",
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  bottomBarButton: {
    flex: 1,
    minHeight: 56,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    gap: 3,
  },
  bottomBarButtonPrimary: { flex: 1.15 },
  bottomBarButtonText: { fontSize: 14, fontWeight: "800" },
  bottomBarButtonLabel: { fontSize: 11, fontWeight: "700", letterSpacing: 0.3 },
  smallText: { fontSize: 12 },
  overlay: { ...StyleSheet.absoluteFillObject, zIndex: 29 },
  drawer: { position: "absolute", top: 0, bottom: 0, left: 0, width: "84%", zIndex: 30, paddingHorizontal: 16, paddingBottom: 20, shadowColor: "#020617", shadowOpacity: 0.24, shadowRadius: 22, shadowOffset: { width: 6, height: 0 }, elevation: 18 },
  drawerTitle: { fontSize: 28, fontWeight: "900", marginBottom: 14, letterSpacing: -0.6 },
  drawerSubtitle: { fontSize: 13, lineHeight: 18, marginTop: -6, marginBottom: 14 },
  drawerTab: { borderRadius: 16, paddingHorizontal: 14, paddingVertical: 12, borderWidth: 1, marginBottom: 8 },
  drawerTabInner: { flexDirection: "row", alignItems: "center", gap: 10 },
  drawerTabText: { fontSize: 14, fontWeight: "700" },
  drawerContent: { gap: 12, paddingBottom: 20 },
  drawerCard: { borderRadius: 24, padding: 16, gap: 12, shadowColor: "#0f172a", shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  sectionDivider: { height: 1, opacity: 0.7 },
  sectionEyebrow: { fontSize: 11, fontWeight: "800", textTransform: "uppercase", letterSpacing: 1.1 },
  sectionHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  sectionHeaderTextBlock: { flex: 1, gap: 4 },
  sectionIconWrap: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  sectionDescription: { fontSize: 13, lineHeight: 19 },
  statPillRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  statPill: { borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1 },
  statPillLabel: { fontSize: 12, fontWeight: "700" },
  heroValueLarge: { fontSize: 28, fontWeight: "900", letterSpacing: -0.8 },
  sectionTitle: { fontSize: 19, fontWeight: "900", letterSpacing: -0.3 },
  groupModeRow: { flexDirection: "row", gap: 8, marginBottom: 6 },
  groupModeButton: { flex: 1, borderRadius: 16, borderWidth: 1, paddingVertical: 11, alignItems: "center" },
  groupModeButtonText: { fontSize: 13, fontWeight: "800" },
  groupCode: { fontSize: 22, fontWeight: "900", letterSpacing: -0.4 },
  inlineActionRow: { flexDirection: "row", gap: 8 },
  inlineActionButton: { flex: 1 },
  memberRow: { paddingVertical: 8, borderBottomWidth: 1 },
  memberIdentity: { flexDirection: "row", gap: 10, alignItems: "center" },
  memberTextBlock: { flex: 1, gap: 2 },
  memberName: { fontSize: 14, fontWeight: "700" },
  countrySelectionRow: { flexDirection: "row", alignItems: "center", gap: 12, borderWidth: 1, borderRadius: 12, padding: 12 },
  countrySelectionTextBlock: { flex: 1, gap: 2 },
  countryTick: { width: 24, height: 24, borderRadius: 8, borderWidth: 1.5, alignItems: "center", justifyContent: "center" },
  countryTickText: { fontSize: 13, fontWeight: "800" },
  avatar: { width: 42, height: 42, borderRadius: 999, backgroundColor: "#cbd5e1" },
  avatarPreview: { width: 88, height: 88, borderRadius: 16, alignSelf: "center" },
  avatarPlaceholder: { width: 42, height: 42, borderRadius: 999, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  avatarPlaceholderText: { fontSize: 16, fontWeight: "800" },
  groupMemberMarker: {
    width: 34,
    height: 34,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0f172a",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 8,
  },
  groupMemberMarkerText: { color: "#ffffff", fontSize: 14, fontWeight: "900" },
  savedGroupCard: { borderWidth: 1, borderRadius: 18, padding: 13, gap: 4 },
  detailsCard: { position: "absolute", left: 16, right: 16, zIndex: 15, padding: 16, borderRadius: 24, maxHeight: "60%", shadowColor: "#0f172a", shadowOpacity: 0.16, shadowRadius: 18, shadowOffset: { width: 0, height: 12 }, elevation: 10 },
  scrollGap: { gap: 10 },
  cardTitle: { fontSize: 18, fontWeight: "900", marginBottom: 6, letterSpacing: -0.3 },
  cardTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 4 },
  cardMetaPill: { alignSelf: "flex-start", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1 },
  cardMetaText: { fontSize: 11, fontWeight: "800", letterSpacing: 0.5, textTransform: "uppercase" },
  heroValue: { fontSize: 13, lineHeight: 18, fontWeight: "600" },
  formCard: { borderRadius: 18, padding: 14 },
  label: { fontSize: 12, textTransform: "uppercase", marginBottom: 4 },
  value: { fontSize: 14, marginBottom: 6 },
  input: { borderWidth: 1, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 12, fontSize: 14, marginBottom: 8 },
  inputCompact: { marginBottom: 0 },
  textarea: { minHeight: 88 },
  primaryButton: { borderRadius: 16, paddingVertical: 13, alignItems: "center" },
  primaryButtonText: { color: "#ffffff", fontSize: 14, fontWeight: "800" },
  secondaryButton: { borderRadius: 16, paddingVertical: 12, alignItems: "center", borderWidth: 1 },
  secondaryButtonText: { fontSize: 14, fontWeight: "800" },
  disabledButton: { opacity: 0.55 },
  ratingRow: { flexDirection: "row", justifyContent: "space-between", gap: 8, marginBottom: 10 },
  ratingCircle: { width: 48, height: 48, borderRadius: 999, borderWidth: 2, alignItems: "center", justifyContent: "center" },
  ratingText: { fontSize: 14, fontWeight: "800" },
  markerDot: {
    minWidth: 26,
    height: 26,
    paddingHorizontal: 8,
    borderRadius: 999,
    borderWidth: 3,
    borderColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0f172a",
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  markerCount: { color: "#ffffff", fontSize: 11, fontWeight: "800" },
  markerSingleDot: { width: 8, height: 8, borderRadius: 999, backgroundColor: "#ffffff" },
  listStack: { gap: 10 },
  errorText: { color: "#ef4444", fontSize: 13 },
});
